const topTrigger = document.getElementById('top-trigger');
const panel = document.getElementById('panel');
const menuToggle = document.getElementById('menuToggle');
const fileInput = document.getElementById('file');
const fileButton = document.getElementById('fileButton');
const columnsSelect = document.getElementById('columns');
const filterSelect = document.getElementById('filter');
const toggleAutoBtn = document.getElementById('toggleAuto');
const speedInput = document.getElementById('speed');
const volumeInput = document.getElementById('volume');
const ignoreSubdirsCheckbox = document.getElementById('ignoreSubdirs');
const emptyPrompt = document.getElementById('empty-prompt');
const viewport = document.getElementById('viewport');
const container = document.getElementById('container');
const reshuffleBtn = document.getElementById('reshuffleBtn');
const mediaStatusEl = document.getElementById('mediaStatus');
const regexInput = document.getElementById('regexFilter');
const hotkeyIcon = document.getElementById('hotkeyIcon');
const themeToggle = document.getElementById('themeToggle');
const dirList = document.getElementById('dirList');
const loadBtn = document.getElementById('loadBtn');
const shuffleToggle = document.getElementById('shuffleToggle');
const dropOverlay = document.getElementById('dropOverlay');
const topBar = document.getElementById('top-bar');
const topRight = document.getElementById('top-right');
const panelClose = document.getElementById('panelClose');

/* Apply config to DOM elements */
if (CONFIG.columns != null) columnsSelect.value = String(CONFIG.columns);
if (CONFIG.filter != null) filterSelect.value = CONFIG.filter;
if (CONFIG.shuffle != null) shuffleToggle.checked = CONFIG.shuffle;
if (CONFIG.speed != null) speedInput.value = CONFIG.speed;
if (CONFIG.speedMin != null) speedInput.min = CONFIG.speedMin;
if (CONFIG.speedMax != null) speedInput.max = CONFIG.speedMax;
if (CONFIG.volume != null) volumeInput.value = CONFIG.volume;
if (CONFIG.volumeStep != null) volumeInput.step = CONFIG.volumeStep;
if (CONFIG.ignoreSubdirs != null) ignoreSubdirsCheckbox.checked = CONFIG.ignoreSubdirs;
if (CONFIG.regexFilter != null) regexInput.value = CONFIG.regexFilter;
